# Generated by Django 4.1.10 on 2023-09-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0122_auto_20230803_1553'),
        ('accounts', '0014_virtualaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbackupautomation',
            name='receiving_asset_one',
            field=models.ManyToManyField(blank=True, related_name='receiving_asset_one_plans', to='assets.asset', verbose_name='Receiving asset one'),
        ),
        migrations.AddField(
            model_name='accountbackupautomation',
            name='receiving_asset_two',
            field=models.ManyToManyField(blank=True, related_name='receiving_asset_two_plans', to='assets.asset', verbose_name='Receiving asset one'),
        ),
    ]
