# Generated by Django 3.1.14 on 2022-07-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0090_auto_20220412_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalauthbook',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical AuthBook', 'verbose_name_plural': 'historical AuthBooks'},
        ),
        migrations.AddField(
            model_name='authbook',
            name='allow_change_auth',
            field=models.BooleanField(default=True, verbose_name='Allow change auth'),
        ),
        migrations.AddField(
            model_name='historicalauthbook',
            name='allow_change_auth',
            field=models.BooleanField(default=True, verbose_name='Allow change auth'),
        ),
        migrations.AlterField(
            model_name='historicalauthbook',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
