# Generated by Django 4.1.13 on 2024-12-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0128_auto_20240514_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_connection_time',
            field=models.DateTimeField(null=True, verbose_name='Last connection time'),
        ),
    ]
