# Generated by Django 4.1.13 on 2024-09-02 07:30

from django.db import migrations, models


def migrate_period_to_statistical_cycle(apps, schema_editor):
    report_model = apps.get_model('reports', 'Report')
    db_alias = schema_editor.connection.alias
    for instance in report_model.objects.using(db_alias).all():
        instance.statistical_cycle = {'period': instance.period}
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='statistical_cycle',
            field=models.JSONField(default=dict, verbose_name='Statistical cycle'),
        ),
        migrations.RunPython(migrate_period_to_statistical_cycle),
        migrations.RemoveField(
            model_name='report',
            name='period',
        ),
    ]
