# Generated by Django 4.1.13 on 2024-06-18 06:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '00128_create_platform_worker'),
        ('accounts', '0020_alter_accountbackupautomation_backup_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('input', models.CharField(blank=True, max_length=1024, verbose_name='输入')),
                ('output', models.CharField(blank=True, max_length=1024, verbose_name='输出')),
                ('index', models.IntegerField(db_index=True, verbose_name='索引')),
                ('status', models.CharField(default='waiting', max_length=32, verbose_name='状态')),
                ('execution_id', models.CharField(max_length=36, verbose_name='Execution')),
                ('timestamp', models.IntegerField(db_index=True, default=0)),
                ('category', models.CharField(default='command', max_length=16, verbose_name='类别')),
                ('pause', models.BooleanField(default=False, verbose_name='Pause')),
            ],
            options={
                'verbose_name': '命令',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('assets', models.ManyToManyField(to='assets.asset', verbose_name='资产')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
            ],
            options={
                'verbose_name': 'Iteration',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
            ],
            options={
                'verbose_name': 'Worker',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.host',),
        ),
        migrations.CreateModel(
            name='Playback',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playbacks', to='behemoth.environment', verbose_name='Environment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('strategy', models.CharField(choices=[('failed_continue', 'Failed continue'), ('failed_stop', 'Failed stop')], default='failed_stop', max_length=32, verbose_name='策略')),
                ('category', models.CharField(choices=[('sync', 'Sync'), ('deploy', 'Deploy')], default='deploy', max_length=32, verbose_name='类别')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='账号')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='资产')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='behemoth.environment', verbose_name='Environment')),
                ('playback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='behemoth.playback', verbose_name='Playback')),
            ],
            options={
                'verbose_name': 'Plan',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('index', models.IntegerField(db_index=True, verbose_name='索引')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='behemoth.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Instruction',
                'ordering': ('-date_created', 'index'),
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('plan_id', models.CharField(max_length=36, verbose_name='Plan')),
                ('plan_meta', models.JSONField(default=dict, verbose_name='Plan meta')),
                ('user_id', models.CharField(max_length=36, verbose_name='用户')),
                ('reason', models.CharField(default='-', max_length=512, verbose_name='原因')),
                ('status', models.CharField(default='not_started', max_length=32, verbose_name='状态')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='账号')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e2s', to='assets.asset', verbose_name='资产')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e1s', to='behemoth.worker', verbose_name='Worker')),
            ],
            options={
                'verbose_name': '任务',
                'ordering': ['-date_created'],
            },
        ),
    ]
