# Generated by Django 4.1.13 on 2024-06-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behemoth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplan',
            name='index',
        ),
        migrations.AddField(
            model_name='subplan',
            name='serial',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Serial'),
        ),
    ]
