# Generated by Django 4.1.13 on 2024-06-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behemoth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplan',
            name='status',
        ),
    ]
