# Generated by Django 4.1.13 on 2024-07-04 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('behemoth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='playback_id',
        ),
        migrations.AlterField(
            model_name='command',
            name='input',
            field=models.TextField(blank=True, verbose_name='输入'),
        ),
        migrations.AlterField(
            model_name='subplan',
            name='plan',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='behemoth.plan', verbose_name='Plan'),
        ),
        migrations.CreateModel(
            name='PlaybackExecution',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('plan_name', models.CharField(max_length=128, verbose_name='Plan name')),
                ('sub_plan_name', models.CharField(max_length=128, verbose_name='Sub plan name')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='behemoth.execution', verbose_name='Execution')),
                ('playback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='behemoth.playback', verbose_name='Playback')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
