# Generated by Django 4.1.13 on 2024-07-25 05:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_accountbackupautomation_backup_type_and_more'),
        ('assets', '0127_automation_remove_account'),
        ('behemoth', '0002_remove_execution_playback_id_command_relation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectExtend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('obj_id', models.UUIDField(verbose_name='Model object')),
                ('meta', models.JSONField(default=dict, verbose_name='元数据')),
                ('category', models.CharField(max_length=128, verbose_name='类别')),
            ],
            options={
                'verbose_name': 'Object extend',
            },
        ),
        migrations.RemoveField(
            model_name='syncplancommandrelation',
            name='sync_plan',
        ),
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ('date_created',), 'verbose_name': '任务'},
        ),
        migrations.AlterModelOptions(
            name='playbackexecution',
            options={'ordering': ('date_created',)},
        ),
        migrations.RemoveField(
            model_name='command',
            name='category',
        ),
        migrations.RemoveField(
            model_name='command',
            name='relation_id',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='plan_meta',
        ),
        migrations.RemoveField(
            model_name='playbackexecution',
            name='sub_plan_name',
        ),
        migrations.AddField(
            model_name='command',
            name='has_delete',
            field=models.BooleanField(default=False, verbose_name='删除'),
        ),
        migrations.AddField(
            model_name='execution',
            name='account_username',
            field=models.CharField(default='-', max_length=128, verbose_name='Account username'),
        ),
        migrations.AddField(
            model_name='execution',
            name='asset_name',
            field=models.CharField(default='-', max_length=128, verbose_name='Asset name'),
        ),
        migrations.AddField(
            model_name='execution',
            name='category',
            field=models.CharField(choices=[('file', '文件'), ('cmd', '命令'), ('pause', 'Pause')], default='cmd', max_length=32, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='execution',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='execution',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='behemoth.plan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='version',
            field=models.CharField(default='', max_length=32, verbose_name='版本'),
        ),
        migrations.AddField(
            model_name='playbackexecution',
            name='meta',
            field=models.JSONField(default=dict, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.database', verbose_name='资产'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='playback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='behemoth.playback', verbose_name='Playback'),
        ),
        migrations.DeleteModel(
            name='SubPlan',
        ),
        migrations.DeleteModel(
            name='SyncPlanCommandRelation',
        ),
    ]
