# Generated by Django 4.1.13 on 2024-07-29 08:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_accountbackupautomation_backup_type_and_more'),
        ('assets', '0127_automation_remove_account'),
        ('behemoth', '0002_remove_execution_playback_id_command_relation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectExtend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('obj_id', models.UUIDField(verbose_name='模型对象')),
                ('meta', models.JSONField(default=dict, verbose_name='元数据')),
                ('category', models.CharField(max_length=128, verbose_name='类别')),
            ],
            options={
                'verbose_name': '对象拓展',
            },
        ),
        migrations.RemoveField(
            model_name='syncplancommandrelation',
            name='sync_plan',
        ),
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ('date_created',), 'verbose_name': '任务'},
        ),
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ('-date_created', 'index'), 'verbose_name': '指令'},
        ),
        migrations.AlterModelOptions(
            name='iteration',
            options={'verbose_name': '迭代'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('-date_created',), 'verbose_name': '计划'},
        ),
        migrations.AlterModelOptions(
            name='playbackexecution',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': '工作机'},
        ),
        migrations.RemoveField(
            model_name='command',
            name='category',
        ),
        migrations.RemoveField(
            model_name='command',
            name='relation_id',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='plan_meta',
        ),
        migrations.RemoveField(
            model_name='playbackexecution',
            name='sub_plan_name',
        ),
        migrations.AddField(
            model_name='command',
            name='has_delete',
            field=models.BooleanField(default=False, verbose_name='删除'),
        ),
        migrations.AddField(
            model_name='execution',
            name='account_username',
            field=models.CharField(default='-', max_length=128, verbose_name='账号用户名'),
        ),
        migrations.AddField(
            model_name='execution',
            name='asset_name',
            field=models.CharField(default='-', max_length=128, verbose_name='资产名称'),
        ),
        migrations.AddField(
            model_name='execution',
            name='category',
            field=models.CharField(choices=[('file', '文件'), ('cmd', '命令'), ('pause', '暂停')], default='cmd', max_length=32, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='execution',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='execution',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='behemoth.plan', verbose_name='计划'),
        ),
        migrations.AddField(
            model_name='execution',
            name='version',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='版本'),
        ),
        migrations.AddField(
            model_name='playbackexecution',
            name='meta',
            field=models.JSONField(default=dict, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='command',
            name='execution_id',
            field=models.CharField(max_length=36, verbose_name='执行'),
        ),
        migrations.AlterField(
            model_name='command',
            name='pause',
            field=models.BooleanField(default=False, verbose_name='暂停'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='task_id',
            field=models.CharField(default='', max_length=36, verbose_name='任务ID'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e1s', to='behemoth.worker', verbose_name='工作机'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='behemoth.plan', verbose_name='计划'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.database', verbose_name='资产'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='category',
            field=models.CharField(choices=[('sync', '同步'), ('deploy', '部署')], default='deploy', max_length=32, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='behemoth.environment', verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_strategy',
            field=models.CharField(choices=[('failed_continue', '失败继续'), ('failed_stop', '失败停止')], default='failed_stop', max_length=32, verbose_name='计划策略'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='playback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='behemoth.playback', verbose_name='回放'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='playback_strategy',
            field=models.CharField(choices=[('auto', '自动添加'), ('manual', '手动添加'), ('never', '不添加')], default='auto', max_length=32, verbose_name='回放策略'),
        ),
        migrations.AlterField(
            model_name='playback',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playbacks', to='behemoth.environment', verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='playbackexecution',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='behemoth.execution', verbose_name='执行'),
        ),
        migrations.AlterField(
            model_name='playbackexecution',
            name='plan_name',
            field=models.CharField(max_length=128, verbose_name='计划名称'),
        ),
        migrations.AlterField(
            model_name='playbackexecution',
            name='playback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='behemoth.playback', verbose_name='回放'),
        ),
        migrations.DeleteModel(
            name='SubPlan',
        ),
        migrations.DeleteModel(
            name='SyncPlanCommandRelation',
        ),
    ]
