# Generated by Django 4.1.13 on 2024-06-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behemoth', '0002_remove_subplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='task_id',
            field=models.CharField(default='', max_length=36, verbose_name='Task ID'),
        ),
    ]
