# Generated by Django 4.1.13 on 2024-08-06 07:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('behemoth', '0003_objectextend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyVersion',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='playback',
            name='environment',
        ),
        migrations.AddField(
            model_name='plan',
            name='c_type',
            field=models.CharField(default='default', max_length=32, verbose_name='自定义'),
        ),
        migrations.AlterField(
            model_name='command',
            name='timestamp',
            field=models.IntegerField(db_index=True, default=0, verbose_name='时间戳'),
        ),
        migrations.AddField(
            model_name='playback',
            name='monthly_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playbacks', to='behemoth.monthlyversion', verbose_name='Monthly version'),
        ),
    ]
