# Generated by Django 4.1.13 on 2024-07-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0127_automation_remove_account'),
        ('behemoth', '0003_execution_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='assets',
            field=models.ManyToManyField(to='assets.database', verbose_name='资产'),
        ),
    ]
