# Generated by Django 4.1.13 on 2024-08-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behemoth', '0004_monthlyversion_remove_playback_environment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playback',
            name='monthly_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playbacks', to='behemoth.monthlyversion', verbose_name='月度版本'),
        ),
    ]
