# Generated by Django 4.1.13 on 2024-08-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behemoth', '0005_alter_playback_monthly_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='version',
            field=models.CharField(max_length=256, verbose_name='版本'),
        ),
    ]
