# Generated by Django 4.1.13 on 2024-08-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behemoth', '0006_alter_execution_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playback',
            name='monthly_version',
        ),
        migrations.DeleteModel(
            name='MonthlyVersion',
        ),
    ]
