# Generated by Django 4.1.13 on 2024-08-22 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behemoth', '0007_remove_playback_monthly_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='behemoth.plan', verbose_name='计划'),
        ),
    ]
