# Generated by Django 4.1.13 on 2024-09-02 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behemoth', '0008_alter_execution_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='need_review',
            field=models.BooleanField(default=False, verbose_name='Need review'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='behemoth.environment', verbose_name='环境'),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('org_id', 'name')},
        ),
    ]
